#!/bin/sh

set -e

title () {
  echo ""
  echo "-------------------------------"
  echo $1
  echo "-------------------------------"
  echo ""
}

title "Checking site..."
bundle exec rake test

title "checking DNS"
bundle exec github-pages health-check

title "Cleaning up..."
rm -Rf _site
